Lesson4
wanderowski/Kolesa-Upgrade-FE-2021 pull request #4
Opened 2021-10-05 17:27 UTC by wanderowski

Домашнее задание №4

2021-10-06 04:51 UTC, Manchenko requested changes

2021-10-06 04:51 UTC, Manchenko commented on src/scss/common/common.scss
> +.link-undecorated {
Имеет место быть, но вот именно это правило я бы не добавлял.

Цвет все равно приходится задавать обычно отдельно. А вот когда цвет ссылки в тексте такой же как у текса это плохо, пользователь не знает куда кликать. 

Правило для подчеркивания обычно идет единое для всех ссылок в проекте, либо все ссылки подчеркнутые либо все не подчеркнутые.

Мы обычно пишем глобальный стиль на все <a>

**Как пример:**

a {
  text-decoration: none;
  color: $blue
}

А уже в местах где ссылка должна выглядеть иначе перезаписываются стили через классы. 



!!!Так делаем только для ссылок. Писать стили для элементов очень опасная практика. Всегда нужно понимать зачем это делается.

2021-10-06 04:51 UTC, Manchenko commented on src/scss/styles.scss
> +@font-face {
Это все можно закинуть в fonts.scss

2021-10-06 04:51 UTC, Manchenko commented on src/scss/component/cards.scss
> +        @include flex-column;
Обратил внимание что ты везде стили для блоков пишешь внутри конйтнера для блоков. Это немного не верно. Так как ты не сможешь потом достать отдельно стили для карточки без списка карточек.

![image](https://user-images.githubusercontent.com/89577029/136142014-3063de2b-ef5a-4049-8e4c-9159565f58db.png)

Вот сюда ты должен описать все стили для .card

На лекции Вова говорил что не стоит туда писать стили которые двигают блок куда либо. margin, top, left, так же с позиционировании, блок не должен быть вырван из потока(Абсолютом не делать). 


А вот уже все стили для отступов и позиционирование очень хорошо описывать контекстно.

Как пример:

```
.cards .card {
  margin: 50px 0;
}
```

```
<div class='cards'>
    <div class='card'>
          <div class='card__title'></div>
    </div>
</div>
```

!! Эта проблема у тебя везде наблюдается.

2021-10-07 13:39 UTC, Manchenko approved these changes

2021-10-07 13:39 UTC, Manchenko commented on main_page.html
> +                                    <button class="btn btn--blue card__btn">Заказать</button>
`btn` это блок
`btn--blue ` это модификатор

`card__btn` - это элемент. Блок не может быть элементом. Если уже сделал кнопку отдельным блоком, то все дополнительные состояние кнопки нужно заносить через модификатор. Или если эти состояния свойственным именно этому контейнеру, то добавляем их контентно. 


Например: 

```
.card .btn {
   margin: 10px
}
```

2021-10-07 14:33 UTC, wanderowski commented on main_page.html
> +                                    <button class="btn btn--blue card__btn">Заказать</button>
Исправил :)

2021-10-08 21:00 UTC, merged