[Vue] Домашнее задание №2
wanderowski/Kolesa-Upgrade-FE-2021 pull request #9
Opened 2021-10-25 13:42 UTC by wanderowski

Разбил все на компоненты. Добавил функционал согласно ТЗ

2021-10-26 06:35 UTC, Manchenko requested changes

2021-10-26 06:35 UTC, Manchenko commented on vue-kolesa-upgrade/src/components/Card.vue
> +</script>
Это не запрос на изменение, но как рекомендация. Сильно удобнее стили для этого компонента держать в этом же файле. 

Вот такой подход в основном используют при написании VUE прилжений https://ru.vuejs.org/v2/guide/single-file-components.html

но при этом твое решение тоже имеет место быть. это не ошибка.

2021-10-26 06:35 UTC, Manchenko commented on vue-kolesa-upgrade/src/components/User.vue
> +    data() {
Имя и баланс ты берешь из пропсов, data в этом компоненте совсем не нужна

2021-10-26 06:35 UTC, Manchenko commented on vue-kolesa-upgrade/src/App.vue
> +            backup: {},
Разобрался зачем. но все равно название переменной не информативно. Нужно вникать в код что бы понять зачем. Ну как вариант `localList, localData, fullData`

2021-10-27 10:32 UTC, Manchenko commented on vue-kolesa-upgrade/src/App.vue
> +                this.restoreItems();
Совсем не нужный else, ты и так перед if делаешь this.restoreItems();

2021-10-27 10:32 UTC, Manchenko commented on vue-kolesa-upgrade/src/App.vue
> +        searchCard(title) {
title - назвнаие аргмента вводит в заблуждение. Тут лучше searchValue назвать

2021-10-27 10:32 UTC, Manchenko commented on vue-kolesa-upgrade/src/App.vue
> +                this.clothes = this.clothes.filter((item) =>
и вообще я бы сдалал бы это computed свойством. 

```
clearClothesData() {
  let clearData = [];
  
  if (this.searchValue !== '') {
     clearData = this.clothes.filter((item) =>item.title.includes(this.searchValue));      
  } else {
      clearData = this.clothes;
  }
  
  return  clearData;
},
```


И уже на основе этого массива стороил дерево. А в этом методе просто перезаписывал бы  this.searchValue

тогда тебе не нужно будет хравнить этот backup

2021-10-27 17:14 UTC, wanderowski commented on vue-kolesa-upgrade/src/App.vue
> +                this.clothes = this.clothes.filter((item) =>
Исправил. Но ведь в таком случае я везде использую clearClothesData и clearAccessoriesData. Смысл будто бы тот же, что и хранить переменнную backup

2021-10-27 17:15 UTC, wanderowski commented on vue-kolesa-upgrade/src/App.vue
> +        searchCard(title) {
Исправил

2021-10-27 17:15 UTC, wanderowski commented on vue-kolesa-upgrade/src/App.vue
> +                this.restoreItems();
Верно :) Спасибо!

2021-10-27 17:15 UTC, wanderowski commented on vue-kolesa-upgrade/src/App.vue
> +            backup: {},
Исправил

2021-10-27 17:16 UTC, wanderowski commented on vue-kolesa-upgrade/src/components/Card.vue
> +</script>
Да, понимаю, но просто мы в предудыщих уроках разбивали все на отдельные файлы, поэтому решил оставить как есть. Спасибо за совет!)

2021-10-30 10:28 UTC, merged